### ISSUE TITLE
Globals in the example

### ISSUE THREAD

**Issue by agladysh** [stetre/luajack#2]
The example in README promotes bad coding practices — all variables there are global. Please do use the `local` keyword where appropriate.

**Comment by stetre** [comment]
Hi, thank you for the remark. Maybe I should add a disclaimer, instead, warning that the example (and all of my code) is not intended to promote coding practices, programming styles, or the like. Those things are in the Realm of the Arguable and everybody has his/her opinions and taste on the matter. I personally like global by default (I also like C pointers...), and when I feel there is no real need to change that behavior I usually stick with it.

**Comment by agladysh** [comment]
Fair enough. Please consider adding a [CONTRIBUTING](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) file then, so no one would be confused :)
