### ISSUE TITLE
Unable to open Jack client

### ISSUE THREAD

**Issue by theGreatWhiteShark** [stetre/luajack#7]
Since I updated my system I can not get the *luajack* module working and I do not know why. Are there any implicit requirements for the Jack server?

I'm using Jack2 version 1.9.12 in classical mode (no DBus interfact activated).

Whenever I want to use *luajack* I get the following error message.

``` lua
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> jack = require 'luajack'
> client = jack.client_open( 'client' )
> client
94558435200432
> jack.client_name( client )
stdin:1: invalid client reference
stack traceback:
	[C]: in function 'luajack.client_name'
	stdin:1: in main chunk
	[C]: in ?

```

**Comment by stetre** [comment]
I've not been able to replicate the problem, but I found and fixed a bug that is most likely the culprit.

**Comment by theGreatWhiteShark** [comment]
Yes, this was indeed the culprit. Thanks a lot!
